version: '3.9'
services:
  larabox_app:
    build:
      args:
        user: larabox_user
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: larabox
    container_name: larabox_app
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - larabox_network
  larabox_mysql:
    image: mysql:8.0
    container_name: larabox_mysql
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: larabox_mysql
    ports:
      - '3316:3306'
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - larabox_network
  larabox_nginx:
    image: nginx:1.23
    container_name: larabox_nginx
    ports:
      - '8092:80'
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d
    networks:
      - larabox_network

networks:
  larabox_network:
    driver: bridge
    name: larabox_network
    ipam:
      config:
        - subnet: 10.18.0.0/16
          gateway: 10.18.0.1
volumes:
  mysql-data:
